title: "Howler's"
description: "The Social Playground for Dogs and Their Humans."
url: "https://bigmarwilson.github.io"
theme: minima
markdown: kramdown
baseurl: "/howlers-website"
# Navigation
header_pages:
  - index.md
  - about.md
  - services.md
  - membership.md
  - gallery.md
  - faq.md
  - contact.md

# Build settings
plugins:
  - jekyll-feed
# trigger rebuild
